jenkins_home: /var/lib/jenkins
jenkins_jcasc_dir: "{{ jenkins_home }}/casc_configs"

jenkins_deb: "https://archives.jenkins.io/debian/jenkins_2.528_all.deb"
java_21_jre: "https://download.oracle.com/java/21/archive/jdk-21.0.8_linux-x64_bin.deb"
footconfig: "http://archive.ubuntu.com/ubuntu/pool/main/f/fontconfig/fontconfig_2.13.1-4.2ubuntu5_amd64.deb"
jq: "https://github.com/jqlang/jq/releases/download/jq-1.8.1/jq-linux-amd64"

plugins_download_manager: 
  url: "https://github.com/jenkinsci/plugin-installation-manager-tool/releases/download/2.13.2/jenkins-plugin-manager-2.13.2.jar"
  path: "/usr/local/bin/jenkins-plugin-manager.jar"

host_ip: "192.168.122.99"
host_port: "8080"
agent_ip: "192.168.122.25"