all:
  hosts:
    jenkins-server:
      ansible_host: "{{ host_ip }}"       # IP của máy đích
      ansible_user: ubuntu                 # user đăng nhập SSH
      #ansible_password: "{{ vault_become_password }}"
      #ansible_become_password: "{{ vault_become_password }}"
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    
    jenkins-agent:
      ansible_host: "{{ agent_ip }}"
      ansible_user: ubuntu-agent
      #ansible_password: "{{ vault_become_password }}"
      #ansible_become_password: "{{ vault_become_password }}"
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519