all:
  children:
    jenkins:
      hosts:
        jenkins-master:
          ansible_host: 192.168.122.199
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
          #ansible_become_password: "{{ vault_become_password }}"
