jenkins: 
  credentials:
    system:
      domainCredentials:
        - credentials:
            - string:
                id: "github-pat"
                secret: "{{ vault_github_pat }}"
            - usernamePassword:
                id: "{{ jenkins_sharedlib_credentials_id }}"
                username: "git"
                password: "{{ vault_github_pat }}"