global:
  scrape_interval: 10s

scrape_configs:
  # JOB 1: Giám sát Máy Controller (172.16.4.15)
  - job_name: 'controller_machine'
    static_configs:
      - targets: 
          - 'node-exporter:9100'      # CPU/RAM
          - 'postgres-exporter:9187'  # Database Postgres
        labels:
          role: 'monitoring-server'
          db: 'primary'

  # JOB 2: Giám sát Máy Ảo (192.168.122.143)
  - job_name: 'virtual_machine_1'
    static_configs:
      # Chỉ lấy Web Metrics (Node Exporter + Script)
      - targets: ['192.168.122.143:9100']
        labels:
          env: 'production'
          app: 'rails_passenger'

          # lan 1