---
# handlers file for ./roles/jenkins_agent_role
    - name: Enable & start agent
      become: true
      ansible.builtin.systemd:
        name: "jenkins-agent.service"
        enabled: true
        state: started

    - name: Reload-Daemon
      become: true
      ansible.builtin.command: 
        cmd: sudo systemctl daemon-reload
    
    - name: Reload-Daemon
      become: true
      ansible.builtin.systemd:
        name: "restart jenkins.agent.service"
        state: restarted