    - name: Check if file agent.jar exists
      ansible.builtin.stat:
        path: "{{ agent_home }}/jenkins/agent/agent.jar"
      register: agent_jar_check
    
    - name: Download Jenkins agent.jar
      ansible.builtin.get_url:
        url: "{{ jenkins_url }}/jnlpJars/agent.jar"
        dest: "{{ agent_home }}/jenkins/agent/agent.jar"
        mode: '0755'
        force: true
        validate_certs: false
      when: not agent_jar_check.stat.exists

    - name: Get secret token
      ansible.builtin.shell: |
        curl -s -u "{{ USER | default('admin') }}:{{ jenkins_environment.ADMIN_PASSWORD }}" \
        "{{ jenkins_url }}/computer/{{ AGENT_NAME | default('ubuntu') }}/{{ AGENT_NAME | default('ubuntu') }}.jnlp" | \
        sed -n 's/.*<application-desc><argument>\([a-z0-9]*\).*/\1/p' > {{ agent_home }}/jenkins/agent/agent_secret_token.txt
      args:
        executable: /bin/bash
      changed_when: true

    - name: Create agent startup script
      ansible.builtin.copy:
        dest: "{{ agent_home }}/jenkins/start-agent.sh"
        mode: '0755'
        content: |
          #!/bin/bash
          SECRET=$(cat {{ agent_home }}/jenkins/agent/agent_secret_token.txt)
          exec /usr/bin/java -jar {{ agent_home }}/jenkins/agent/agent.jar -url {{ jenkins_url }} -name "{{ AGENT_NAME }}" -secret $SECRET -webSocket -workDir {{ agent_home }}/jenkins

    - name: Create systemd service to run Jenkins agent
      ansible.builtin.copy:
        dest: /etc/systemd/system/jenkins-agent.service
        content: |
          [Unit]
          Description=Jenkins Agent Service
          After=network.target

          [Service]
          WorkingDirectory={{ agent_home }}/jenkins
          ExecStart={{ agent_home }}/jenkins/start-agent.sh
          Restart=always

          [Install]
          WantedBy=multi-user.target
      become: true