    - name: Check if Java is exists
      ansible.builtin.shell: |
        java --version | head -n 1 | cut -d " " -f 2
      register: java_exist
      ignore_errors: true

    - name: Install java
      ansible.builtin.get_url:
        url: "{{ java_21_jre }}"
        dest: "/tmp/java/"
        mode: "0644"
      when: java_exist.rc != 0 or ('21.0.8' not in java_exist.stdout) 

    - name: Install java if not installed
      ansible.builtin.apt:
        deb: "/tmp/java/jdk-21.0.8_linux-x64_bin.deb"
      when: java_exist.rc != 0 or ('21.0.8' not in java_exist.stdout) 