---
# tasks file for ./roles/jenkins_agent_role
- ansible.builtin.include_tasks: prechecks.yml
  tags: [precheck]

- ansible.builtin.include_tasks: java.yml
  tags: [java]

- ansible.builtin.include_tasks: inbound_connect.yml
  tags: [inbound_connect]

- ansible.builtin.include_tasks: start_&_reload.yml
  tags: [start_&_reload]
