    - name: Apt update
      become: true
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 0

    - name: Ensure Jenkins agent dir
      ansible.builtin.file:
        path: "/home/{{ ansible_user | default('/home/ubuntu') }}/jenkins/agent"
        state: directory
        owner: "{{ ansible_user | default('ubuntu') }}"
        group: "{{ ansible_user | default('ubuntu') }}"
        mode: '0755'

    - name: Ensure Jenkins agent WorkingDirectory
      ansible.builtin.file:
        path: "/home/jenkins/agent"
        state: directory
        owner: "{{ ansible_user | default('ubuntu') }}"
        group: "{{ ansible_user | default('ubuntu') }}"
        mode: '0755'
      become: true