---
- name: Fetch Jenkins inbound agent secret
  hosts: jenkins-agent
  gather_facts: true
  vars_files:
    - ../group_vars/agent/jenkins_agent.yml
    - ../group_vars/all/jenkins.yml
    - ../group_vars/master/jenkins_env.yml
  vars: 
    jenkins_url: "http://{{ CONTROLLER_IP }}:{{ CONTROLLER_PORT}}"
    jar_dest: "/home/{{ ansible_user }}/jenkins/agent/agent.jar"
    agent_home: "/home/{{ ansible_user }}"
  roles:
    - jenkins_agent_role

