    - name: Check if fontconfig is exists
      ansible.builtin.shell: |
        fc-cache -V
      register: fontconfig_exist
      ignore_errors: true

    - name: Install fontconfig
      ansible.builtin.get_url:
        url: "{{ footconfig }}"
        dest: "/tmp/fontconfig/"
        mode: "0644"
      when: fontconfig_exist.rc != 0 or ('fontconfig version 2.13.1' not in fontconfig_exist.stdout) 

    - name: Install fontconfig if not installed
      ansible.builtin.apt:
        deb: "/tmp/fontconfig/fontconfig_2.13.1-4.2ubuntu5_amd64.deb"
      when: fontconfig_exist.rc != 0 or ('fontconfig version 2.13.1' not in fontconfig_exist.stdout) 