---
# tasks file for jenkins_master_role
- ansible.builtin.include_tasks: prechecks.yml
  tags: [precheck]

- ansible.builtin.include_tasks: java.yml
  tags: [java]

- ansible.builtin.include_tasks: fontconfig.yml
  tags: [fontconfig]

- ansible.builtin.include_tasks: deb_install.yml
  tags: [install]

- ansible.builtin.include_tasks: systemd_override.yml
  tags: [service]

- ansible.builtin.include_tasks: envfile.yml
  tags: [env]

- ansible.builtin.include_tasks: plugins.yml
  tags: [plugins]

- ansible.builtin.include_tasks: jcasc.yml
  tags: [jcasc]


- ansible.builtin.include_tasks: service.yml
  tags: [service]
